### ISSUE TITLE
Opção 3 de geração de PDF parou de funcionar

### ISSUE THREAD

**Issue by bhfernandes** [claudiosmweb/wc-boleto-pdf#2]
Bom dia!
Já uso esse excelente plugin a mais de 6 meses e agora ele simplesmente parou de funcionar a opção:
- Convert HTML to PDF online - simplehtmltopdf.com

A opção secundária (Free converter HTML to PDF online - freehtmltopdf.com) funciona, porém leva certa de 30 a 50 segundos para exibir o PDF.

A terceira opção é paga (não cheguei a tentar utilizar).

Segue imagem do erro:
![erro](https://cloud.githubusercontent.com/assets/15001020/17367645/30354728-5967-11e6-8e7b-9d9e57b53373.jpg)

**Comment by claudiosanches** [comment]
Use uma das outras opções.
É um serviço externo, se parou de funcionar é porque parou de funcionar.
